---
title: "DSlecture18"
author: "Hening CUi"
date: "11/17/2021"
output: html_document
---

```{r,echo = FALSE}
library (tidyverse)
library(p8105.datasets)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## import data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

## fit model

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```
lets fit the model

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

lets look at result

```{r, include=FALSE}

fit

summary(fit)

summary(fit)$coef
coef(fit)
```
lets look at result better

```{r}
broom::glance(fit)
broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(term = str_replace(term, "borough", "Borough: ")) %>% 
  knitr::kable(digits = 3)
```

## be in control of factors 

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

look at that plot again

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
broom::tidy(fit)
```

## diagnose

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() +
  ylim(-500, 1500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point() +
  facet_wrap(. ~ borough)
```

## hypothesis test

does t test by default

```{r}
fit %>% 
  broom::tidy()
```

what about significance of borough

```{r}
fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```


## Nest data, fit model

```{r}
fit = lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb) 

broom::tidy(fit)
```

more explore

```{r}
nyc_airbnb %>% 
  nest(data = - borough) %>% 
  mutate(
    modes = map(.x = data, ~lm(price ~ stars, data = .x)),
    results = map (modes, broom::tidy)
  ) %>% 
  select(-data, -modes) %>% 
  unnest(results) %>% 
  select(borough, term, estimate) %>% 
  pivot_wider(
    names_from = borough,
    values_from = estimate
  )
```


nest even more

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  nest(data = - neighborhood) %>% 
  mutate(
    modes = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    results = map (modes, broom::tidy)
  ) %>% 
  select(-data, -modes) %>% 
  unnest(results) %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) +
  geom_point() +
  facet_wrap( ~ term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
  
```

